// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuelGQqi36qy49p5S3VRXo8wu-AZ_SEeA',
    appId: '1:135077801576:web:c22d086855e2116eec95dd',
    messagingSenderId: '135077801576',
    projectId: 'dmaas-17abc',
    authDomain: 'dmaas-17abc.firebaseapp.com',
    storageBucket: 'dmaas-17abc.firebasestorage.app',
    measurementId: 'G-H7PME5M2VT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbOrlSy37G_c_zbWMIKxu1S-vg7sLw9ow',
    appId: '1:135077801576:android:9f88cd8287829e0dec95dd',
    messagingSenderId: '135077801576',
    projectId: 'dmaas-17abc',
    storageBucket: 'dmaas-17abc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXgivO0-IT-nvD3fDvnwhQrG20INdUN8c',
    appId: '1:135077801576:ios:cf95233c557bd517ec95dd',
    messagingSenderId: '135077801576',
    projectId: 'dmaas-17abc',
    storageBucket: 'dmaas-17abc.firebasestorage.app',
    iosClientId: '135077801576-c7a2906jkqhle0adf3bk1c1o2btlbldr.apps.googleusercontent.com',
    iosBundleId: 'ai.predictionlabs.dmaasUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXgivO0-IT-nvD3fDvnwhQrG20INdUN8c',
    appId: '1:135077801576:ios:cf95233c557bd517ec95dd',
    messagingSenderId: '135077801576',
    projectId: 'dmaas-17abc',
    storageBucket: 'dmaas-17abc.firebasestorage.app',
    iosClientId: '135077801576-c7a2906jkqhle0adf3bk1c1o2btlbldr.apps.googleusercontent.com',
    iosBundleId: 'ai.predictionlabs.dmaasUi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuelGQqi36qy49p5S3VRXo8wu-AZ_SEeA',
    appId: '1:135077801576:web:2a70eb1aeb4cf908ec95dd',
    messagingSenderId: '135077801576',
    projectId: 'dmaas-17abc',
    authDomain: 'dmaas-17abc.firebaseapp.com',
    storageBucket: 'dmaas-17abc.firebasestorage.app',
    measurementId: 'G-FQF47JJSGN',
  );

}